linters-settings:
  gocyclo:
    min-complexity: 24
  cyclop:
    max-complexity: 24
  forbidigo:
    forbid:
      - .*\.Fatal.*
      - fmt\.Print.*

linters:
  enable-all: true

  disable:
    - deadcode
    - depguard
    - exhaustive
    - exhaustivestruct
    - exhaustruct
    - golint
    - gomnd
    - ifshort
    - interfacer
    - ireturn
    - maligned
    - nosnakecase
    - varnamelen
    - structcheck
    - scopelint
    - tagalign
    - varcheck
    - wastedassign
    - execinquery

run:
  timeout: 10m
  tests: false
